# Start AeroSpace at login and run no extra startup commands
start-at-login = true
after-login-command = []
after-startup-command = []

# Enable tree normalization for consistent layout
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Accordion (tabbed) layout, zero padding for fullscreen
accordion-padding = 0

# Use accordion for all new workspaces
default-root-container-layout = "accordion"
default-root-container-orientation = "horizontal"

# Remove all gaps for a true fullscreen look
[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.right = 0
outer.top = 0
outer.bottom = 0

[mode.main.binding]
# Workspaces
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-q = "workspace Q"
alt-w = "workspace W"
alt-e = "workspace E"
alt-r = "workspace R"

# Move focused window to workspace
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-q = "move-node-to-workspace Q"
alt-shift-w = "move-node-to-workspace W"
alt-shift-e = "move-node-to-workspace E"
alt-shift-r = "move-node-to-workspace R"

# Workspace back and forth
cmd-backtick = "focus right --boundaries-action wrap-around-the-workspace"

# Move focus across monitors
cmd-alt-ctrl-shift-n = "focus-monitor --wrap-around next"
cmd-alt-ctrl-shift-p = "focus-monitor --wrap-around prev"

[mode.service.binding]
esc = ["reload-config", "mode main"]
r = ["flatten-workspace-tree", "mode main"]
f = ["layout floating tiling", "mode main"]
backspace = ["close-all-windows-but-current", "mode main"]